Internal Server Error: /stationery/generate_custom_printout_report/
Traceback (most recent call last):
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'FieldFile' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\stationery\admin_utils.py", line 147, in generate_custom_printout_report
    return render(request, 'stationery/printouts/report-pdfs.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\template\defaulttags.py", line 241, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\template\base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\db\models\fields\files.py", line 66, in url
    self._require_file()
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\db\models\fields\files.py", line 41, in _require_file
    raise ValueError(
ValueError: The 'file' attribute has no file associated with it.
"POST /stationery/generate_custom_printout_report/ HTTP/1.1" 500 160044
Internal Server Error: /stationery/printout-reports/daily/
Traceback (most recent call last):
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\stationery\admin_utils.py", line 115, in generate_printout_report
    start_date = timezone.make_aware(start_date_naive, timezone=server_timezone)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\utils\timezone.py", line 242, in make_aware
    if is_aware(value):
       ^^^^^^^^^^^^^^^
  File "C:\Users\chanm\Desktop\ClickPick\ClickPick\backend\env\Lib\site-packages\django\utils\timezone.py", line 221, in is_aware
    return value.utcoffset() is not None
           ^^^^^^^^^^^^^^^
AttributeError: 'datetime.date' object has no attribute 'utcoffset'
"GET /stationery/printout-reports/daily/ HTTP/1.1" 500 83628
